code/src/objects/Date_Formats__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Format__c</fullName>
        <defaultValue>&apos;MM-dd-yyyy&apos;</defaultValue>
        <inlineHelpText>Date format (e.g. MM-dd-yyyy)</inlineHelpText>
        <label>Format</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Date Formats</label>
</CustomObject>

code/src/objects/Debugging__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Callout_Debug_Mode__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check for callout debug mode</inlineHelpText>
        <label>Callout Debug Mode</label>
        <type>Checkbox</type>
    </fields>
    <label>Debugging</label>
</CustomObject>

code/src/objects/Endpoints__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Callout_Endpoint__c</fullName>
        <label>Callout Endpoint</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Callout_Timeout__c</fullName>
        <defaultValue>60000</defaultValue>
        <inlineHelpText>Callout timeout in ms</inlineHelpText>
        <label>Callout Timeout (ms)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Endpoints</label>
</CustomObject>

code/src/classes/ConfigurationManager.cls
public class ConfigurationManager{
    
    //global endpoint
    public static String CALLOUT_ENDPOINT{
        get{
            //return 'http://quotesondesign.com/wp-json/posts?filter[orderby]=rand';
            return Endpoints__c.getOrgDefaults().Callout_Endpoint__c;
        }
    }

    //global timeout in ms
    public static Integer CALLOUT_TIMEOUT{
        get{
            //return 60000;
            return Endpoints__c.getOrgDefaults().Callout_Timeout__c.intValue();
        }
    }

    //user/profile centric debug mode
    public static Boolean DEBUG_MODE{
        get{
            //return true;
            return Debugging__c.getInstance().Callout_Debug_Mode__c;
        }
    }

    //returns a specific date format given the locale code
    public static String getDateFormat(String localeCode){
    	
        //if(localeCode == 'it_IT'){
        //    return 'dd/MM/yyyy';
        //}
        //return 'MM/dd/yyyy';*/
    	Date_Formats__c defaultFormat = Date_Formats__c.getInstance('Default');
    	Date_Formats__c localeFormat = Date_Formats__c.getInstance(localeCode);
        if(localeFormat != null) return localeFormat.Format__c;
        return defaultFormat.Format__c;
    }

}